/* PALS Companion — IAP ALS core cases.
   Based on the IAP ALS course core-case format (Evaluate → Identify → Intervene, in four blocks:
   initial impression (PAT), primary (ABCDE), secondary (SAMPLE + focused exam), diagnostics).
   Written in our own words for simulation; clinical data follow the course cases.
   Weights are not given in the cases: they are assumed for age and can be changed in Setup.
   Stage fields used by the controller:
     block     'PAT' | 'Primary' | 'Secondary' | 'Diagnostics' | 'Post-ROSC'
     findings  [label, text] pairs the instructor reads out when the team assesses
     identify  what the team should name (ticked separately from interventions)
     expect    interventions (ticked)
     result    optional {title, text} the instructor can show on the monitor
   Tokens: {adr}, {aden1}, {aden2}, {J0.5}, {J2}, {ml20} (20 mL/kg in mL) etc. are filled from the weight.
   OWNER TO VERIFY all content against the current IAP ALS manual. */
(() => {
'use strict';
const ARREST_V = { hr: 0, spo2: 70, rr: 0, etco2: 3, sbp: 0, dbp: 0 };
const arrest = (rhythm, v, extra) => Object.assign({ rhythm, pulse: false, v: Object.assign({}, ARREST_V, v || {}) }, extra || {});
const live = (rhythm, v, extra) => Object.assign({ rhythm, pulse: true, cpr: false, v }, extra || {});
const PAT_IV = ['Activates the emergency response and delegates roles', 'Starts 100 % O₂ by non-rebreather mask after clearing the airway', 'Attaches cardiac monitor and pulse oximeter'];

const CORE = [
{
  id: 'ia1', num: 1, title: 'Upper airway obstruction',
  pt: { group: 'child', age: '4 y', wt: 16 },
  settings: [
    ['ER', 'Emergency room', 'A 4-year-old girl with fever, difficulty in swallowing and neck swelling for two days is now breathless.'],
    ['Ward', 'General ward', 'A 4-year-old girl admitted with fever, difficulty in swallowing and neck swelling has become breathless over the last 4 hours.'],
    ['ICU', 'ICU', 'A 4-year-old girl with fever, dysphagia and noisy breathing was intubated for airway protection and extubated an hour ago. She now has respiratory distress.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 130, spo2: 89, rr: 36, etco2: 40, sbp: 90, dbp: 60, temp: 37 }), ramp: 0,
      findings: [['Appearance', 'Anxious'], ['Breathing', 'Increased work of breathing with stridor'], ['Colour', 'Pink']],
      identify: ['Potentially life-threatening illness'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 130, spo2: 93, rr: 36 }),
      findings: [['Airway', 'Low-pitched inspiratory stridor'], ['Breathing', 'RR 36, increased effort, suprasternal retractions, reduced breath sounds on both sides; SpO₂ 89 % in room air, 93 % on 100 % O₂'],
        ['Circulation', 'HR 130, narrow-complex rhythm with P waves; central and peripheral pulses well felt; warm; CRT 2 s; BP 90/60'],
        ['Disability', 'Anxious with intermittent drowsiness; pupils equal and reacting; RBS 92 mg/dL'], ['Exposure', 'Temperature 37 °C']],
      identify: ['Respiratory distress / impending respiratory failure', 'Upper airway obstruction'],
      expect: ['Allows position of comfort to keep the airway open', 'Suctions nose and mouth', 'Prepares an advanced airway to protect the airway and bypass the obstruction'] },
    { block: 'Secondary', name: 'Secondary assessment (after intubation)', set: live('sinus', { hr: 116, spo2: 96, rr: 26, sbp: 100, dbp: 68 }, { intubated: true }),
      findings: [['Signs & symptoms', 'Fever, then difficulty in swallowing with rapidly increasing neck swelling over 2 days'], ['Allergies', 'None'], ['Medication', 'Paracetamol 2 h ago'],
        ['Past history', 'Nothing significant, but unimmunised'], ['Last meal', 'Small meal last night'], ['Events', 'Breathlessness'],
        ['HEENT', 'White patch over the tonsils; membrane on the left tonsil; fullness of the left side of the neck; enlarged cervical nodes'],
        ['Heart & lungs', 'No murmur; coarse breath sounds; CRT about 2 s'], ['Neuro', 'Somewhat anxious; no focal deficit'],
        ['Repeat vitals after intubation', 'HR 116, RR 26, SpO₂ 96 % on 100 % O₂, BP 100/68']],
      identify: ['Respiratory distress', 'Upper airway obstruction: suspected diphtheria'],
      expect: ['Sends specific tests for diphtheria', 'Arranges anti-diphtheritic serum (ADS)', 'Prepares for tracheal tube placement'] },
    { block: 'Diagnostics', name: 'Laboratory assessment', set: live('sinus', { hr: 112, spo2: 97, rr: 24 }),
      findings: [['Tests (once stable)', 'CBC with differential, blood culture, throat swab and membrane (if detachable) for fungus, Albert stain for diphtheria, Gram stain and culture; blood calcium, electrolytes, ABG'],
        ['Imaging', 'Only in other causes of stridor where infection is likely']],
      identify: ['Diphtheria (pending confirmation)'], expect: ['ADS and definitive management as per results', 'ENT consultation if required'] },
  ],
},
{
  id: 'ia2', num: 2, title: 'Lower airway obstruction',
  pt: { group: 'infant', age: '9 mo', wt: 8 },
  settings: [
    ['ER', 'Emergency room', 'A 9-month-old girl with cough, cold and breathlessness for 6 hours.'],
    ['Ward', 'General ward', 'A 9-month-old girl admitted this morning with cough and breathlessness now has increasing difficulty in breathing.'],
    ['ICU', 'ICU', 'A 9-month-old girl admitted with cough and breathlessness has worsening breathlessness.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 145, spo2: 93, rr: 51, etco2: 46, sbp: 79, dbp: 49, temp: 37 }, { co2Shape: 'obstructive' }), ramp: 0,
      findings: [['Appearance', 'Anxious'], ['Breathing', 'Increased rate and effort, audible wheeze'], ['Colour', 'Pink']],
      identify: ['Potentially life-threatening illness'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 145, spo2: 96, rr: 51 }, { co2Shape: 'obstructive' }),
      findings: [['Airway', 'No secretions; wheeze heard'], ['Breathing', 'RR 51, increased effort, intercostal retractions, good chest rise, bilateral expiratory wheeze; SpO₂ 93 % in room air, 96 % on 100 % O₂'],
        ['Circulation', 'HR 145, sinus rhythm; central and peripheral pulses well felt; warm; CRT 2 s; BP 79/49'],
        ['Disability', 'Anxious; pupils equal and reacting; RBS 84 mg/dL'], ['Exposure', 'Temperature 37 °C']],
      identify: ['Respiratory distress / respiratory failure', 'Lower airway obstruction'],
      expect: ['Evaluates the response to 100 % O₂', 'Prepares salbutamol nebulisation (or MDI with spacer)', 'Considers vascular access'] },
    { block: 'Secondary', name: 'Secondary assessment', set: live('sinus', { hr: 130, spo2: 96, rr: 50, sbp: 84, dbp: 50 }, { co2Shape: 'obstructive' }),
      findings: [['Signs & symptoms', 'Coryza and cough for 1 day; breathless for 6 hours'], ['Allergies', 'None'], ['Medication', 'Cough syrup from an old prescription 4 h ago'],
        ['Past history', 'Recurrent cough treated with inhalers in the past; not on a preventer'], ['Last meal', '4 hours ago'], ['Events', 'Breathing worse, feeding less'],
        ['Exam', 'HEENT, heart and abdomen normal; no oedema, rash or atopy; anxious'],
        ['Repeat vitals after O₂', 'HR 130, RR 50, SpO₂ 96 % on 100 % O₂, BP 84/50']],
      identify: ['Respiratory distress', 'Lower airway obstruction'],
      expect: ['Lets the child keep a position of comfort', 'Salbutamol nebulisation every 20 min with O₂ (or MDI + spacer every 10 min) for one hour', 'Considers HHFNC / nCPAP if no response after three nebulisations or if worsening'] },
    { block: 'Diagnostics', name: 'Laboratory assessment', set: live('sinus', { hr: 128, spo2: 97, rr: 44 }, { co2Shape: 'obstructive' }),
      findings: [['Tests (once stable)', 'Serum electrolytes, ABG'], ['Imaging', 'Chest X-ray']],
      identify: ['Lower airway obstruction'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia3', num: 3, title: 'Parenchymal lung disease',
  pt: { group: 'toddler', age: '18 mo', wt: 10 },
  settings: [
    ['ER', 'Emergency room', 'An 18-month-old with fever, cough and breathlessness for one day.'],
    ['Ward', 'General ward', 'An 18-month-old admitted with fever, cough and breathlessness, on nasal-cannula O₂ at 2 L/min, now has increased breathlessness. The nurse calls you.'],
    ['ICU', 'ICU', 'An 18-month-old admitted with fever, cough and breathlessness for one day has increased breathlessness.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 133, spo2: 91, rr: 53, etco2: 44, sbp: 104, dbp: 65, temp: 38.9 }), ramp: 0,
      findings: [['Appearance', 'Lethargic'], ['Breathing', 'Increased rate and effort with grunting'], ['Colour', 'Pink']],
      identify: ['Potentially life-threatening illness'], expect: ['Calls for help and delegates after explaining the urgency', 'High-flow 100 % O₂ by NRM after clearing the airway if needed', 'Attaches monitors and pulse oximeter'] },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 133, spo2: 100, rr: 53 }),
      findings: [['Airway', 'Copious secretions in the mouth'], ['Breathing', 'RR 53, intercostal and subcostal retractions, good chest rise, bilateral diffuse crepitations, grunting; SpO₂ 91 % in room air, 100 % on NRM'],
        ['Circulation', 'HR 133, sinus rhythm; central and peripheral pulses normal; CRT 2 s; BP 104/65'],
        ['Disability', 'Lethargic; pupils equal and reacting; RBS 78 mg/dL'], ['Exposure', 'Temperature 102 °F; no rash, petechiae or bleeding']],
      identify: ['Respiratory distress vs respiratory failure'],
      expect: ['Opens the airway and suctions the oropharynx', 'Gives oxygen', 'Prepares non-invasive support (CPAP or HHFNC) if worsening'] },
    { block: 'Secondary', name: 'Secondary assessment', set: live('sinus', { hr: 122, spo2: 100, rr: 50 }),
      findings: [['Signs & symptoms', 'Fever, cough and breathlessness for one day'], ['Allergies / medication / past illness', 'None'], ['Last meal', 'Last night'], ['Events', 'Worsening breathing difficulty and grunting'],
        ['Exam', 'HEENT normal; S1 S2 normal, no murmur; abdomen normal; alert'],
        ['Repeat vitals after NRM', 'RR 50 with intercostal and subcostal retractions, audible grunting, bilateral diffuse crepitations; SpO₂ 100 %; HR 122, sinus; good pulses; CRT 2 s; pink']],
      identify: ['Respiratory failure (lung tissue disease)'],
      expect: ['Obtains vascular access (IV / IO)', 'Gives appropriate IV antibiotics', 'Starts CPAP; if worse, bag-mask ventilation or intubation with bag-tube ventilation'] },
    { block: 'Diagnostics', name: 'Laboratory assessment', set: live('sinus', { hr: 124, spo2: 97, rr: 46, etco2: 52 }),
      findings: [['Tests', 'ABG, serum electrolytes, renal function, CBC with differential, blood culture (if not done)'], ['Chest X-ray', 'Bilateral pulmonary infiltrates']],
      result: { title: 'ABG · Chest X-ray', text: 'ABG: hypoxaemia with raised PaCO₂\nChest X-ray: bilateral pulmonary infiltrates' },
      identify: ['Respiratory failure (ABG: hypoxaemia with raised PaCO₂)'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia4', num: 4, title: 'Disordered control of breathing',
  pt: { group: 'toddler', age: '16 mo', wt: 10 },
  settings: [
    ['ER', 'Emergency room', 'A 16-month-old who had a seizure at home is brought in post-ictal with difficulty in breathing.'],
    ['Ward', 'General ward', 'A 16-month-old admitted 2 days ago with fever and seizures had a recurrence 15 minutes ago, followed by difficulty in breathing.'],
    ['ICU', 'ICU', 'A 16-month-old admitted with fever and seizures for 2 days had a recurrence 15 minutes ago, followed by difficulty in breathing.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 133, spo2: 70, rr: 8, etco2: 60, sbp: 84, dbp: 50, temp: 37 }), ramp: 0,
      findings: [['Appearance', 'No spontaneous movements, unresponsive'], ['Breathing', 'Irregular, slow, gasping efforts'], ['Colour', 'Dusky']],
      identify: ['Acute life-threatening illness'], expect: ['Calls for help and delegates', '100 % O₂ and asks for bag and mask after clearing the airway', 'Attaches monitors and pulse oximeter'] },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 133, spo2: 70, rr: 8, etco2: 60 }),
      findings: [['Airway', 'Secretions in the mouth'], ['Breathing', 'Irregular, slow, gasping efforts; poor chest rise; conducted sounds; SpO₂ 70 % on NRM'],
        ['Circulation', 'HR 133, sinus rhythm; central and peripheral pulses present; CRT 2 s; BP 84/50'],
        ['Disability', 'Obtunded, not interacting; pupils equal and reacting; RBS 90 mg/dL'], ['Exposure', 'Temperature 37 °C; no rash, petechiae or bleeding']],
      identify: ['Respiratory failure: disordered control of breathing'],
      expect: ['Starts bag-mask ventilation with 100 % O₂'] },
    { block: 'Secondary', name: 'Secondary assessment (after BMV)', set: live('sinus', { hr: 122, spo2: 100, rr: 25, etco2: 42 }),
      findings: [['Signs & symptoms', 'Fever for 2 days; one generalised tonic-clonic seizure 2 days ago'], ['Allergies', 'None known'],
        ['Medication', 'IV midazolam, IV phenytoin load then maintenance; midazolam and a phenytoin mini-load for the recurrence; IV antibiotic'],
        ['Past illness', 'None'], ['Last meal', 'Last night'], ['Events', 'Generalised tonic-clonic seizure 15 min ago, then unresponsive'],
        ['Repeat vitals after BMV with 100 % O₂', 'Good chest rise, SpO₂ 100 %, HR 122 sinus, good pulses, CRT 2 s'],
        ['Exam', 'HEENT, heart, abdomen normal; no rash or bleeding; obtunded with minimal response to pain']],
      identify: ['Respiratory failure: disordered control of breathing'],
      expect: ['Prepares non-invasive positive-pressure ventilation or endotracheal intubation', 'Obtains vascular access (IV / IO)'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 120, spo2: 99, rr: 25 }),
      findings: [['Tests', 'ABG, serum electrolytes, renal function, CBC, blood cultures, lumbar puncture (if not done)'], ['Imaging', 'Chest X-ray, CECT head']],
      identify: ['Cause of the seizures and respiratory depression (per results)'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia5', num: 5, title: 'Hypovolaemic shock',
  pt: { group: 'toddler', age: '1½ y', wt: 10 },
  settings: [
    ['ER', 'Emergency room', 'A one-and-a-half-year-old girl with vomiting and loose motions for a day has become lethargic over the last half hour.'],
    ['Ward', 'General ward', 'A one-and-a-half-year-old girl admitted with vomiting and loose motions has now become lethargic.'],
    ['ICU', 'ICU', 'A one-and-a-half-year-old girl admitted with vomiting and loose motions has now become lethargic.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 138, spo2: 93, rr: 36, etco2: 30, sbp: 90, dbp: 67, temp: 36.7 }), ramp: 0,
      findings: [['Appearance', 'Lethargic'], ['Breathing', 'Normal'], ['Colour', 'Pale']],
      identify: ['Acute life-threatening problem: possible shock'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 138, spo2: 97, rr: 36 }),
      findings: [['Airway', 'Open and clear'], ['Breathing', 'RR 36, no recessions, good chest rise, equal breath sounds; SpO₂ 93 % in room air, 97 % on NRM'],
        ['Circulation', 'HR 138, sinus rhythm; central pulses good, peripheral weak; cold; CRT 3–4 s; BP 90/67'],
        ['Disability', 'Lethargic; pupils normal and reacting; RBS 84 mg/dL'], ['Exposure', 'Pale; temperature 98 °F']],
      identify: ['Shock, compensated (? hypovolaemic)'],
      expect: ['Continues 100 % O₂ by NRM', 'Obtains vascular access (IV / IO)', 'Isotonic crystalloid (NS / RL) bolus 20 mL/kg = {ml20}', 'Reassesses after the bolus'] },
    { block: 'Secondary', name: 'Secondary assessment (after O₂ + bolus)', set: live('sinus', { hr: 148, spo2: 100, rr: 32 }),
      findings: [['Signs & symptoms', 'Loose motions, vomiting and fever for one day'], ['Allergies / medication / past illness', 'None'], ['Last meal', 'Last night'],
        ['Exam', 'Sunken eyes, dry mucosa, decreased skin turgor; heart normal; no oedema or rash; lethargic'],
        ['Repeat vitals after O₂ and a fluid bolus', 'RR 32, no retractions; SpO₂ 100 % on NRM; HR 148 sinus; good central, feeble peripheral pulses; CRT 3–4 s; pale']],
      identify: ['Hypovolaemic shock, still compensated'],
      expect: ['Repeats a rapid isotonic bolus 20 mL/kg = {ml20}', 'Prepares advanced haemodynamic monitoring and PICU transfer if no response'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 136, spo2: 99, rr: 30 }),
      findings: [['Tests', 'ABG, serum electrolytes, renal function, CBC, blood cultures (if not done)'], ['Chest X-ray', 'For heart size and lung fields']],
      result: { title: 'ABG', text: 'Metabolic acidosis with partial respiratory compensation' },
      identify: ['Metabolic acidosis with partial respiratory compensation'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia6', num: 6, title: 'Obstructive shock',
  pt: { group: 'infant', age: '6 mo', wt: 7 },
  settings: [
    ['ICU', 'ICU', 'A 6-month-old baby on a ventilator becomes agitated and cyanosed after a bout of cough. You are in charge of the patient and the nurse calls you.'],
    ['ER', 'Emergency room', 'A 6-month-old baby being transported on manual IPPR becomes restless and turns blue as the attendants shift the patient from the ambulance to the ER.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 170, spo2: 67, rr: 30, etco2: 50, sbp: 64, dbp: 30, temp: 37.1 }, { intubated: true }), ramp: 0,
      findings: [['Appearance', 'Agitated'], ['Breathing', 'On ventilator / manual IPPR'], ['Colour', 'Cyanosed']],
      identify: ['Acute life-threatening situation'],
      expect: ['Calls for help and delegates', 'Ensures 100 % O₂ by bag and tube after detaching from the ventilator', 'Attaches / confirms monitors and pulse oximeter'] },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 170, spo2: 67, rr: 30 }, { intubated: true }),
      findings: [['Airway', 'ETT 4 mm fixed at 12 cm; mist present'], ['Breathing', 'Asymmetric chest rise (less on the right); decreased air entry on the right, left normal; no added sounds; SpO₂ 67 %'],
        ['Circulation', 'HR 170, sinus rhythm; central and peripheral pulses feeble; CRT 3–4 s; BP 64/30'],
        ['Disability', 'Agitated'], ['Exposure', 'Temperature 98.8 °F; skin normal']],
      identify: ['Respiratory failure'],
      expect: ['Removes from the ventilator and ventilates with bag and tube, 100 % O₂', 'Uses DOPE (Displacement, Obstruction, Pneumothorax, Equipment) to identify a right pneumothorax', 'Needle decompression: 2nd right intercostal space, mid-clavicular line, just above the 3rd rib'] },
    { block: 'Primary', name: 'Re-evaluation after needle decompression', set: live('sinus', { hr: 156, spo2: 89, rr: 30, sbp: 68, dbp: 40 }, { intubated: true }), ramp: 10000,
      findings: [['Airway', 'ETT at the same level; mist present'], ['Breathing', 'Gush of air; chest rise improving on the right, so is air entry; no added sounds; SpO₂ 89 %'],
        ['Circulation', 'HR 156, sinus rhythm; central pulses improved, peripheral pulses poor; CRT 3 s; BP 68/40']],
      identify: ['Obstructive and hypotensive shock'],
      expect: ['Arranges an intercostal drain (ICD) with underwater seal', 'Considers a 5–10 mL/kg bolus ({ml5}–{ml10}) over 20–30 min while reassessing cardiopulmonary status'] },
    { block: 'Secondary', name: 'Secondary assessment (after thoracostomy)', set: live('sinus', { hr: 140, spo2: 98, rr: 28, etco2: 42, sbp: 76, dbp: 44 }, { intubated: true }),
      findings: [['Signs & symptoms', 'Pneumonia, recently intubated after failing HFNC; depth of insertion noted'], ['Allergies', 'None known'], ['Medication', 'IV fluids'],
        ['Last meal', 'Tube feed 2 hours ago'], ['Events', 'Bout of cough followed by sudden deterioration'],
        ['Repeat vitals after thoracostomy and 100 % O₂', 'HR 140, RR 28 (assisted), SpO₂ 98 % (would have worsened if not done)'],
        ['Exam', 'HEENT / neck normal; abdomen distended; back normal; extremities normal']],
      identify: ['Hypotensive obstructive shock', 'Tension pneumothorax'],
      expect: ['Inserts the ICD', 'Counsels the parents'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 138, spo2: 98, rr: 28 }, { intubated: true }),
      findings: [['Tests (once stable)', 'ABG / VBG'], ['Imaging', 'Chest X-ray, but do not wait for it before intervening']],
      identify: ['Tension pneumothorax (confirm ICD position on X-ray)'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia7', num: 7, title: 'Septic shock',
  pt: { group: 'toddler', age: '2 y', wt: 12 },
  settings: [
    ['ER', 'Emergency room', 'A 2-year-old boy with fever since the morning, vomiting and refusal of feeds for a day, lethargic since the morning.'],
    ['Ward', 'General ward', 'A 2-year-old boy with nephrotic syndrome has fever for one day and abdominal pain, with altered sensorium.'],
    ['ICU', 'ICU', 'A 2-year-old boy after surgery for appendicitis develops fever, abdominal pain and lethargy.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 190, spo2: 95, rr: 55, etco2: 28, sbp: 67, dbp: 34, temp: 39.4 }), ramp: 0,
      findings: [['Appearance', 'Drowsy'], ['Breathing', 'Increased rate and effort'], ['Colour', 'Pale']],
      identify: ['Life-threatening illness'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 190, spo2: 97, rr: 55 }),
      findings: [['Airway', 'Open and clear'], ['Breathing', 'RR 55, subcostal recessions, equal expansion, good air entry, no added sounds; SpO₂ 97 % on 100 % O₂'],
        ['Circulation', 'HR 190, sinus rhythm; bounding central and peripheral pulses; CRT < 2 s; warm, flushed skin; BP 67/34'],
        ['Disability', 'Lethargic; pupils normal; RBS 48 mg/dL'], ['Exposure', 'Temperature 103 °F; skin otherwise normal']],
      identify: ['Hypotensive shock: ? distributive (septic)', 'Hypoglycaemia'],
      expect: ['100 % O₂ by NRM', 'IV / IO access and samples', 'NS / RL 20 mL/kg = {ml20} rapid push-pull (three-way stopcock)', '10 % dextrose 5 mL/kg = {ml5} IV / IO', 'Prepared for up to three boluses'] },
    { block: 'Secondary', name: 'Secondary assessment (after fluid + dextrose)', set: live('sinus', { hr: 140, spo2: 99, rr: 32, sbp: 70, dbp: 32 }),
      findings: [['Signs & symptoms', 'Fever for one day with vomiting and lethargy'], ['Allergies', 'None'], ['Medication', 'Antipyretics only, as an outpatient'],
        ['Past history', 'Nothing remarkable'], ['Last meal', 'Usual food, but vomited afterwards'], ['Events', 'Fever, lethargy, vomiting, no improvement'],
        ['Exam', 'Gaseous abdominal distension; lethargic before fluid and dextrose, better afterwards'],
        ['Repeat vitals after O₂ and bolus', 'Lethargic; HR 140, RR 32 with increased work of breathing; bounding pulses; CRT < 2 s; SpO₂ 99 %; BP 70/32; RBS 86 mg/dL']],
      identify: ['Septic (distributive) shock, still hypotensive'],
      expect: ['Another 20 mL/kg NS / RL over 15–20 min while shock end-points are not met', 'Watches for volume overload', 'Gives the first dose of antibiotic', 'Prepares elective intubation if shock persists', 'Prepares vasoactive infusion (noradrenaline) if shock persists after three boluses', 'Measures urine output; prepares PICU transfer'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 136, spo2: 99, rr: 30, sbp: 82, dbp: 44 }),
      findings: [['Tests', 'CBC with differential and platelets, peripheral smear, blood cultures, ABG/VBG, serum lactate'], ['Imaging', 'Chest X-ray, abdominal ultrasound for abscess or fluid']],
      identify: ['Source of sepsis (per results)'], expect: ['Treatment as per response and results'] },
  ],
},
{
  id: 'ia8', num: 8, title: 'Cardiogenic shock',
  pt: { group: 'toddler', age: '2 y', wt: 12 },
  settings: [
    ['OPD', 'Outpatients', 'A 2-year-old boy with cough, coryza and low-grade fever for 3 days is not feeding today, is lethargic and breathing fast.'],
    ['Ward', 'General ward', 'A 2-year-old boy admitted for hernia surgery has low-grade fever and some cough, is not feeding well and not interacting for a day, with fast breathing.'],
    ['ICU', 'ICU', 'A 2-year-old boy admitted with low-grade fever, cough and coryza for 3 days is shifted to the ICU for increasing breathlessness.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 181, spo2: 98, rr: 56, etco2: 30, sbp: 82, dbp: 55, temp: 37.8 }), ramp: 0,
      findings: [['Appearance', 'Lethargic'], ['Breathing', 'Increased rate and effort'], ['Colour', 'Cyanosed']],
      identify: ['Life-threatening illness'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 181, spo2: 100, rr: 56 }),
      findings: [['Airway', 'No secretions'], ['Breathing', 'RR 56, intercostal retractions, adequate chest rise, equal air entry, fine basal crackles both sides; SpO₂ 98 % in room air, 100 % on 100 % O₂'],
        ['Circulation', 'HR 181, sinus rhythm; central pulses good, peripheral poor; cold, clammy, dusky skin; CRT > 3 s; BP 82/55'],
        ['Disability', 'Drowsy; pupils normal; RBS 76 mg/dL'], ['Exposure', 'Mild abdominal distension; cold dusky skin']],
      identify: ['Shock, compensated'],
      expect: ['100 % O₂ by NRM', 'Gains vascular access, IV saline', 'Proceeds to the secondary assessment to characterise the shock'] },
    { block: 'Secondary', name: 'Secondary assessment', set: live('sinus', { hr: 172, spo2: 100, rr: 50, sbp: 84, dbp: 56 }),
      findings: [['Signs & symptoms', 'Mild cough and coryza with low-grade fever for 3 days, poor feeding, breathless for a few hours'], ['Allergies', 'None'],
        ['Medication', 'Cough syrup and antipyretics on and off for 2 weeks'], ['Past history', 'Not significant'], ['Events', 'Lethargic and not feeding since the morning'],
        ['Exam', 'Gallop rhythm, muffled heart sounds, no murmur; liver palpable 4 cm below the costal margin; lethargic']],
      identify: ['Compensated cardiogenic shock: ? viral myocarditis', 'Improved on O₂ and a small bolus'],
      expect: ['Restricts fluid to a 5 mL/kg NS bolus = {ml5}', 'Arranges inotropes and PICU transfer', 'Prepared to ventilate', 'Calls the paediatric cardiologist; plans investigations'] },
    { block: 'Diagnostics', name: 'Laboratory diagnosis', set: live('sinus', { hr: 165, spo2: 99, rr: 46 }),
      findings: [['Tests', 'CBC with differential, electrolytes with calcium, CPK-MB, troponin T, ABG'], ['ECG / imaging', '12-lead ECG, chest X-ray, echocardiography']],
      identify: ['Viral myocarditis likely'], expect: ['Corrects metabolic derangements', 'Prognosticates with the family'] },
  ],
},
{
  id: 'ia9', num: 9, title: 'Supraventricular tachycardia',
  pt: { group: 'child', age: '4 y', wt: 16 },
  settings: [
    ['ER', 'Emergency room', 'A 4-year-old with lethargy, difficulty in breathing and refusal to eat for one day.'],
    ['Ward', 'Ward', 'A 4-year-old admitted in the ward has had difficulty in breathing and agitation for a few hours.'],
    ['ICU', 'ICU', 'A 4-year-old admitted for unexplained lethargy.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('svt', { hr: 292, spo2: 93, rr: 68, etco2: 32, sbp: 87, dbp: 68, temp: 37 }), ramp: 0,
      findings: [['Appearance', 'Agitated'], ['Breathing', 'Increased rate, laboured'], ['Colour', 'Dusky']],
      identify: ['Potentially life-threatening illness'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('svt', { hr: 292, spo2: 98, rr: 68 }),
      findings: [['Airway', 'Oral secretions'], ['Breathing', 'RR 68, equal expansion, intercostal retractions, fine basal crepitations; SpO₂ 93 %, 98 % on O₂'],
        ['Circulation', 'HR 292, narrow QRS, fast rhythm, P waves absent, no variability; central and peripheral pulses adequate; CRT 2 s; BP 87/68; passed urine 3 h ago'],
        ['Disability', 'Awake, GCS 15/15; pupils equal and reacting; RBS 130 mg/dL'], ['Exposure', 'Temperature 37 °C; no rash or bleeding']],
      identify: ['Respiratory distress', 'Supraventricular tachycardia with adequate perfusion'],
      expect: ['Ice packs to the face without compromising the airway', 'IV access with a three-way for adenosine 0.1 mg/kg = {aden1}, rapid NS flush', 'Repeats with 0.2 mg/kg = {aden2} if needed', 'Prepares synchronised cardioversion if required', 'Orders a 12-lead ECG; calls the cardiologist'] },
    { block: 'Secondary', name: 'Secondary assessment (after vagal + 2 doses adenosine)', set: live('svt', { hr: 248, spo2: 100, rr: 58 }),
      findings: [['Signs & symptoms', 'Mild upper respiratory symptoms; suddenly unwell since last night; looks dull'], ['Allergies / medication / past illness', 'None; no similar illness before'],
        ['Last meal', 'Last night'], ['Events', 'Lethargic since the morning'],
        ['Exam', 'Tachycardia, no murmur; tender hepatomegaly 3 cm; no oedema; GCS 15/15, a bit lethargic'],
        ['Repeat vitals after O₂, vagal manoeuvres and two doses of adenosine', 'HR 248, RR 58, SpO₂ 100 %']],
      identify: ['Respiratory distress: SVT persisting'],
      expect: ['Synchronised cardioversion 0.5–1 J/kg ({J0.5}–{J1}) with sedation if possible', 'Repeats synchronised cardioversion if needed', 'Takes help from the cardiologist'] },
    { block: 'Secondary', name: 'After synchronised cardioversion', set: live('sinus', { hr: 120, spo2: 100, rr: 40 }), ramp: 5000,
      findings: [['After cardioversion', 'HR comes down to 120/min, sinus rhythm']],
      identify: ['Sinus rhythm restored'], expect: ['Reassesses ABCDE after conversion'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 118, spo2: 100, rr: 34 }),
      findings: [['Tests', 'Chest X-ray, echo, 12-lead ECG, biomarkers (troponin T, CPK-MB)']],
      identify: ['Cause / complications of SVT (per results)'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia10', num: 10, title: 'Bradycardia (snake bite)',
  pt: { group: 'toddler', age: '2 y', wt: 12 },
  settings: [
    ['Pre-hospital', 'Pre-hospital', 'You are called to examine a 2-year-old boy who was bitten by a snake while playing in the field and has become lethargic.'],
    ['ER', 'Emergency room', 'A 2-year-old boy is brought with a history of snake bite and has become lethargic with shallow breathing.'],
  ],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: live('sinus', { hr: 40, spo2: 68, rr: 12, etco2: 55, sbp: 80, dbp: 56, temp: 37 }), ramp: 0,
      findings: [['Appearance', 'Altered sensorium, vacant look'], ['Breathing', 'Slow, shallow breathing'], ['Colour', 'Pale']],
      identify: ['Acute life-threatening situation'], expect: PAT_IV },
    { block: 'Primary', name: 'Primary assessment', set: live('sinus', { hr: 40, spo2: 68, rr: 12 }),
      findings: [['Airway', 'Clear'], ['Breathing', 'RR 12, reduced work of breathing and chest expansion, equal air entry, no added sounds; SpO₂ 68 %'],
        ['Circulation', 'HR 40, sinus rhythm; central pulses normal, peripheral feeble; CRT 3 s; BP 80/56'],
        ['Disability', 'Reduced responsiveness, hypotonia; RBS 86 mg/dL'], ['Exposure', 'Afebrile; no rash']],
      identify: ['Bradycardia + bradypnoea = hypoxia', 'Cardiopulmonary failure', 'Bradycardia with reduced perfusion'],
      expect: ['Bag-mask ventilation with 100 % O₂', 'Evaluates the HR response to ventilation and oxygen', 'Ready to start chest compressions', 'IV / IO access, saline bolus, samples', 'Proceeds to the secondary assessment'] },
    { block: 'Secondary', name: 'Secondary assessment (after BMV)', set: live('sinus', { hr: 55, spo2: 98, rr: 20, etco2: 42, sbp: 78, dbp: 60 }),
      findings: [['Signs & symptoms', 'Bitten by a snake while playing in the field; lethargic soon after; unresponsive for 1 h'], ['Allergies / medication / past history', 'None'],
        ['Last meal', 'Breakfast this morning'], ['Events', 'Lethargy soon after the bite'],
        ['Repeat vitals after BMV', 'HR 55, RR 20 on BMV, SpO₂ 98 %, BP 78/60, CRT < 2 s, peripheral pulses well felt'],
        ['Exam', 'No dehydration; heart normal; abdomen normal; snake-bite mark near the left ankle, swollen and red; chest clear; no focal deficit, pupils equal']],
      identify: ['Bradycardia with adequate perfusion'],
      expect: ['Removes constricting objects (anklets) and immobilises the limb', 'Supports oxygenation and ventilation; CPR if required', 'Arranges anti-snake venom and a venom detection kit', 'Watches for anaphylaxis, shock, neurotoxicity, coagulopathy and AKI using Evaluate-Identify-Intervene'] },
    { block: 'Diagnostics', name: 'Diagnostic tests', set: live('sinus', { hr: 70, spo2: 98, rr: 20 }),
      findings: [['Tests', 'Blood calcium, electrolytes, urea, creatinine, ABG, coagulation profile']],
      identify: ['Envenomation complications (per results)'], expect: ['Definitive management as per results'] },
  ],
},
{
  id: 'ia11', num: 11, title: 'Asystole / PEA (drowning)',
  pt: { group: 'toddler', age: '1 y', wt: 10 },
  settings: [['ER', 'Emergency room', 'A one-year-old child is fished out of the pond near home.']],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: arrest('asystole', { temp: 36 }), ramp: 0,
      findings: [['Appearance', 'No spontaneous movements, unresponsive'], ['Breathing', 'No spontaneous efforts'], ['Colour', 'Dusky, mottled']],
      identify: ['Cardiac arrest'],
      expect: ['Activates the emergency response', 'Starts high-quality CPR with chest compressions and hands over to another provider as help arrives', 'Starts bag-mask ventilation with 100 % O₂', 'Attaches monitors including the defibrillator'] },
    { block: 'Primary', name: 'Primary assessment', set: arrest('asystole', { rr: 20 }),
      findings: [['Airway', 'Oral secretions; neck floppy'], ['Breathing', 'No spontaneous efforts; chest rise obtained with BMV and 100 % O₂; SpO₂ not reading'],
        ['Circulation', 'Central pulses absent; monitor shows asystole; further examination deferred'], ['Disability', 'No spontaneous movements, unresponsive, limp'], ['Exposure', 'Deferred']],
      identify: ['Asystole'],
      expect: ['Continues high-quality CPR', 'Establishes vascular access (IV / IO)', 'Adrenaline 0.01 mg/kg = {adr} with saline flush, every 3–5 min', 'Rotates compressors every 2 min', 'Reassesses the rhythm every 2 min'] },
    { block: 'Secondary', name: 'Reversible causes (during CPR)', set: arrest('asystole', { rr: 20 }),
      findings: [['Approach', 'Look for reversible causes (H\'s and T\'s) while continuing high-quality CPR; SAMPLE history and focused exam deferred until ROSC'],
        ['Glucose', 'Random blood sugar 42 mg/dL']],
      result: { title: 'Bedside glucose', text: 'RBS 42 mg/dL' },
      identify: ['Asystole', 'Hypoglycaemia'],
      expect: ['10 % dextrose 5 mL/kg = {ml5} IV / IO, then NS / RL bolus 20 mL/kg = {ml20}', 'Reviews other H\'s and T\'s', 'Continues CPR 15:2 with BMV', 'Briefs the family', 'Considers intubation if ventilation is not adequate'] },
    { block: 'Post-ROSC', name: 'After ROSC', set: live('sinus', { hr: 140, spo2: 94, rr: 25, etco2: 44, sbp: 80, dbp: 46 }), ramp: 20000,
      findings: [['Vitals', 'Not given in the case: adjust to suit your teaching'], ['Tests (after ROSC)', 'Blood calcium, electrolytes, ABG, toxicology screen']],
      identify: ['Return of spontaneous circulation'], expect: ['Definitive management as per test results'] },
  ],
},
{
  id: 'ia12', num: 12, title: 'VF / VT (trauma)',
  pt: { group: 'toddler', age: '2 y', wt: 12 },
  settings: [['ER', 'Emergency room', 'A 2-year-old was struck by an automobile and is brought to your hospital.']],
  stages: [
    { block: 'PAT', name: 'Initial impression', set: arrest('vt', { hr: 125 }), ramp: 0,
      findings: [['Appearance', 'Unresponsive'], ['Breathing', 'No breathing'], ['Colour', 'Pale']],
      identify: ['Cardiac arrest'],
      expect: ['Calls for help and starts high-quality CPR', 'Delegates chest compressions and coordinates CPR', 'Starts bag-mask ventilation with 100 % O₂ after clearing the airway', 'Attaches monitors / defibrillator and pulse oximeter'] },
    { block: 'Primary', name: 'Primary assessment', set: arrest('vt', { hr: 125, rr: 20 }),
      findings: [['Airway', 'Secretions in the mouth and throat'], ['Breathing', 'Not breathing; chest rise adequate and symmetrical with BMV; equal air entry; no added sounds; SpO₂ not reading'],
        ['Circulation', 'Monitor HR 110–140, wide-complex QRS; pulses not palpable; CRT prolonged; BP not recordable'],
        ['Disability', 'No spontaneous movements, unresponsive, limp'],
        ['Exposure', 'Warm; bruises over the left parietal region, left face, shoulder, chest and thigh; swollen left thigh; abdomen soft but distended']],
      identify: ['Cardiac arrest: collapse rhythm pulseless ventricular tachycardia'],
      expect: ['Continues high-quality CPR', 'Defibrillates at 2–4 J/kg ({J2}–{J4}), up to 10 J/kg', 'Resumes CPR straight after the shock without a pulse check', 'Prepares adrenaline 0.01 mg/kg = {adr} during CPR; gives it after the second rhythm check, then every 3–5 min', 'Rotates the compressor and reassesses the rhythm every 2 min', 'Considers H\'s and T\'s; has amiodarone {amio} / lignocaine {lido} ready'] },
    { block: 'Secondary', name: 'Rhythm check after 2 min: VF', set: arrest('vf', { rr: 20 }),
      findings: [['Approach', 'SAMPLE history deferred'], ['Rhythm check', 'After two minutes, pulse check before the next defibrillation: rhythm is now VF'], ['Think', 'Intrathoracic and intra-abdominal injuries']],
      identify: ['Ventricular fibrillation', 'Intrathoracic and intra-abdominal injuries'],
      expect: ['Continues CPR and the shockable-rhythm algorithm', 'IV fluids', 'Surgical consults for chest and abdominal injuries', 'Arranges blood'] },
    { block: 'Post-ROSC', name: 'After ROSC', set: live('sinus', { hr: 150, spo2: 94, rr: 25, etco2: 42, sbp: 76, dbp: 44 }), ramp: 20000,
      findings: [['Vitals', 'Not given in the case: adjust to suit your teaching'], ['Tests (after ROSC)', 'Haemogram, liver and kidney function, ABG, chest X-ray']],
      identify: ['Post-arrest stabilisation needed'], expect: ['Post-arrest stabilisation and definitive management as per results'] },
  ],
},
];

CORE.forEach(c => {
  c.cat = 'IAP ALS core cases';
  c.core = true;
  c.title = `Core case ${c.num}: ${c.title}`;
  c.stem = c.settings[0][2];
});
PC.SCENARIOS = CORE.concat(PC.SCENARIOS || []);
})();
