/* PALS Companion — scenario library (instructor-only text; never shown on the monitor).
   Stage `set` is merged into the monitor state; `v` values drift over `ramp` ms (default 15 s).
   {adr}, {amio}, … and {J2} (J at 2 J/kg) are filled in with the patient's weight.
   OWNER TO VERIFY every dose, energy and cue against current AHA PALS / IAP guidance and unit protocol. */
(() => {
'use strict';
// Arrest stages leave CPR as it is (the instructor toggles it when the team starts/stops).
const ARREST = { pulse: false, v: { hr: 0, spo2: 70, rr: 0, etco2: 3, sbp: 0, dbp: 0 } };
const arrest = (rhythm, extra) => Object.assign({}, ARREST, { rhythm }, extra || {}, { v: Object.assign({}, ARREST.v, (extra && extra.v) || {}) });

PC.SCENARIOS = [
{
  id: 'vf', cat: 'Arrest', title: 'Sudden collapse: VF',
  pt: { group: 'child', age: '8 y', wt: 25, bed: 'Resus 1' },
  stem: 'An 8-year-old boy collapsed while playing football. He is brought into the emergency room unresponsive. You are the resuscitation team.',
  stages: [
    { name: 'Unresponsive: VF', set: arrest('vf'), ramp: 0,
      cues: ['Team should confirm: unresponsive, not breathing, no pulse (≤10 s).', 'Turn CPR ON (Live tab) when compressions start; set RR ≈ 10–20 once ventilating.', 'Pads on: VF is shockable, so shock {J2}.'],
      expect: ['Recognises arrest and starts CPR within 10 s', 'High-quality CPR: 100–120/min, ≥⅓ AP depth, full recoil', 'Identifies VF as shockable', 'Shocks at 2 J/kg ({J2}) with minimal pause', 'Resumes CPR immediately after the shock'] },
    { name: 'After 1st shock: still VF', set: arrest('vf', { v: { rr: 20 } }),
      cues: ['Continue 2-min CPR cycle; swap compressor.', 'IV/IO access.', 'At rhythm check: still VF, so shock {J4}, then adrenaline {adr}.'],
      expect: ['Obtains IV/IO access during CPR', 'Second shock at 4 J/kg ({J4})', 'Adrenaline {adr} after 2nd shock', 'Compressor swapped every 2 min'] },
    { name: 'After 2nd shock: still VF', set: arrest('vf', { v: { rr: 20 } }),
      cues: ['Shock ≥4 J/kg (max 10 J/kg or adult dose).', 'Amiodarone {amio} or lidocaine {lido}.', 'Ask the team for reversible causes (H\'s and T\'s).'],
      expect: ['Third shock ≥4 J/kg', 'Gives amiodarone {amio} or lidocaine {lido}', 'Verbalises H\'s and T\'s', 'Adrenaline repeated every 3–5 min'] },
    { name: 'ROSC', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 135, spo2: 95, rr: 20, etco2: 42, sbp: 86, dbp: 48 } }, ramp: 20000,
      cues: ['Watch whether the team notices the EtCO₂ jump and the pleth returning.', 'Post-ROSC: SpO₂ 94–99 %, avoid hypotension, check glucose, temperature control, PICU.'],
      expect: ['Recognises ROSC (pulse, EtCO₂ rise, pleth)', 'Titrates O₂ to SpO₂ 94–99 %', 'Measures BP and treats hypotension', 'Checks glucose and electrolytes', 'Arranges PICU / post-arrest care'] },
  ],
},
{
  id: 'asys', cat: 'Arrest', title: 'Drowning: asystole → PEA',
  pt: { group: 'toddler', age: '2 y', wt: 12, bed: 'Resus 1' },
  stem: 'A 2-year-old was pulled out of a water sump after an unknown time. Bystanders started CPR. She arrives limp and blue.',
  stages: [
    { name: 'Pulseless: asystole', set: arrest('asystole', { v: { temp: 34.5 } }), ramp: 0,
      cues: ['Drowning: oxygenation and ventilation first; 15:2 with two rescuers.', 'Non-shockable: give adrenaline {adr} as soon as IV/IO access is in.', 'Temperature 34.5 °C: see whether they notice.'],
      expect: ['Starts CPR with effective ventilation', 'Identifies asystole: does not shock', 'Early IV/IO and adrenaline {adr}', 'Confirms asystole (leads, gain)'] },
    { name: 'CPR ongoing: PEA', set: arrest('sinus', { v: { hr: 48, rr: 20, temp: 34.5 } }),
      cues: ['Organised rhythm on screen but no pulse = PEA. The monitor raises NO rhythm alarm, only "SpO₂ NO PULSE".', 'Repeat adrenaline every 3–5 min.', 'Reversible causes: hypoxia, hypothermia.'],
      expect: ['Checks pulse and identifies PEA', 'Does not shock PEA', 'Repeats adrenaline at 3–5 min', 'Addresses hypoxia and hypothermia'] },
    { name: 'ROSC', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 118, spo2: 91, rr: 24, etco2: 48, sbp: 78, dbp: 42, temp: 34.8 } }, ramp: 20000,
      cues: ['Post-ROSC: ventilation targets, avoid hyperoxia, treat hypotension, check glucose, avoid hyperthermia when rewarming.'],
      expect: ['Recognises ROSC', 'Post-ROSC bundle: SpO₂, BP, glucose, temperature', 'Plans PICU transfer'] },
  ],
},
{
  id: 'pea', cat: 'Arrest', title: 'Dehydration shock → PEA',
  pt: { group: 'infant', age: '8 mo', wt: 7, bed: 'Resus 2' },
  stem: 'An 8-month-old with 3 days of diarrhoea and vomiting is drowsy, with cold extremities and a capillary refill time of 5 seconds.',
  stages: [
    { name: 'Hypotensive shock', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 195, spo2: 95, rr: 50, etco2: 28, sbp: 58, dbp: 32, temp: 37.9 } }, ramp: 0,
      cues: ['Hypotensive for age (SBP < 70 + 2×age). IV/IO within 90 s, then IO.', 'Bolus {bolus}, reassess after each; check glucose.'],
      expect: ['Recognises hypotensive shock', 'Rapid IV/IO access', 'Gives 10–20 mL/kg bolus and reassesses', 'Checks glucose'] },
    { name: 'Arrest: PEA', set: arrest('sinus', { v: { hr: 65, rr: 20 } }),
      cues: ['Organised slow rhythm, no pulse, no pleth.', 'CPR, adrenaline {adr}; hypovolaemia is the reversible cause: push fluids.'],
      expect: ['Recognises PEA and starts CPR', 'Adrenaline {adr}', 'Identifies hypovolaemia and gives fluid bolus during CPR'] },
    { name: 'ROSC after fluids', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 172, spo2: 96, rr: 40, etco2: 36, sbp: 72, dbp: 40 } }, ramp: 20000,
      cues: ['Continue fluid resuscitation with reassessment; electrolytes, glucose, urine output.'],
      expect: ['Recognises ROSC', 'Reassesses perfusion before each bolus', 'Sends electrolytes and blood gas'] },
  ],
},
{
  id: 'svt', cat: 'Rhythm', title: 'SVT in an infant (stable)',
  pt: { group: 'infant', age: '3 mo', wt: 5.5, bed: 'Resus 2' },
  stem: 'A 3-month-old has been irritable and feeding poorly for 12 hours. Mother noticed fast breathing. He is pink and alert, with a capillary refill time of 2 seconds.',
  stages: [
    { name: 'SVT, perfusing', set: { rhythm: 'svt', pulse: true, cpr: false, v: { hr: 280, spo2: 97, rr: 46, etco2: 35, sbp: 82, dbp: 52 } }, ramp: 0,
      cues: ['Narrow QRS, no visible P, fixed rate > 220: SVT, not sinus tachycardia.', 'Stable: vagal manoeuvre (ice to face), then adenosine {aden1} rapid push + flush.'],
      expect: ['Distinguishes SVT from sinus tachycardia', 'Assesses perfusion and decides "stable"', 'Tries vagal manoeuvre (ice to face)', 'Records a rhythm strip / 12-lead'] },
    { name: 'After vagal: still SVT', set: { rhythm: 'svt', pulse: true },
      cues: ['Adenosine {aden1} via a proximal vein with a two-syringe rapid flush.', 'When they push it, go to the next stage.'],
      expect: ['Adenosine 0.1 mg/kg ({aden1}), rapid push + flush', 'Runs a printed strip during adenosine', 'Prepares {aden2} as the 2nd dose'] },
    { name: 'Adenosine: brief pause', set: { rhythm: 'asystole', pulse: true }, ramp: 0,
      cues: ['A 3–6 s pause is expected. Watch the team\'s reaction, then press Next.'],
      expect: ['Team stays calm and waits for a pause, not CPR'] },
    { name: 'Sinus rhythm', set: { rhythm: 'sinus', pulse: true, v: { hr: 150, rr: 40 } }, ramp: 5000,
      cues: ['Converted. Discuss cardiology referral and a 12-lead ECG (look for pre-excitation).'],
      expect: ['Confirms sinus rhythm on a 12-lead', 'Plans cardiology follow-up'] },
  ],
},
{
  id: 'svtu', cat: 'Rhythm', title: 'Unstable SVT: cardioversion',
  pt: { group: 'child', age: '4 y', wt: 16, bed: 'Resus 1' },
  stem: 'A 4-year-old with palpitations for 1 day is now lethargic and grey, with a capillary refill time of 5 seconds and weak pulses.',
  stages: [
    { name: 'SVT with poor perfusion', set: { rhythm: 'svt', pulse: true, cpr: false, v: { hr: 250, spo2: 94, rr: 36, etco2: 32, sbp: 66, dbp: 40 } }, ramp: 0,
      cues: ['Unstable (hypotension, altered consciousness): synchronised cardioversion {J0.5}–{J1}.', 'Adenosine only if IV is already in and it does not delay cardioversion. Sedate if possible.', 'Turn SYNC on in the Live tab when they arm the defibrillator.'],
      expect: ['Recognises instability', 'Chooses synchronised cardioversion', 'Turns SYNC on and checks sync markers', 'Energy 0.5–1 J/kg ({J0.5}–{J1})', 'Safe "all clear" before shock'] },
    { name: 'After 1st shock: still SVT', set: { rhythm: 'svt', pulse: true },
      cues: ['Increase to {J2}. Check that SYNC is re-armed (many devices reset it).'],
      expect: ['Increases energy to 2 J/kg ({J2})', 'Re-confirms SYNC before the 2nd shock'] },
    { name: 'Sinus rhythm', set: { rhythm: 'sinus', pulse: true, v: { hr: 130, sbp: 92, dbp: 56, spo2: 97 } }, ramp: 15000,
      cues: ['Reassess, 12-lead ECG, cardiology consult.'],
      expect: ['Reassesses perfusion after conversion', '12-lead ECG and referral'] },
  ],
},
{
  id: 'brady', cat: 'Rhythm', title: 'Hypoxic bradycardia (infant)',
  pt: { group: 'infant', age: '2 mo', wt: 4.5, bed: 'Resus 2' },
  stem: 'A 2-month-old with bronchiolitis has had an apnoeic spell on the ward. He is floppy and cyanosed.',
  stages: [
    { name: 'Apnoeic, HR 55', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 55, spo2: 68, rr: 6, etco2: 62, sbp: 58, dbp: 32 } }, ramp: 0,
      cues: ['Airway + BVM ventilation with O₂ first.', 'HR < 60 with poor perfusion despite effective ventilation means start CPR.', 'Pick a branch once you see their ventilation.'],
      expect: ['Opens airway, starts BVM with O₂', 'Checks chest rise and seal', 'Reassesses HR after ventilation'],
      next: [{ label: 'Effective BVM ▶', to: 1 }, { label: 'Ineffective / still < 60 ▶', to: 2 }] },
    { name: 'Good ventilation: recovering', set: { rhythm: 'sinus', pulse: true, v: { hr: 145, spo2: 95, rr: 30, etco2: 44, sbp: 76, dbp: 44 } }, ramp: 30000,
      cues: ['HR and SpO₂ rise with ventilation. Discuss ongoing support (HFNC/CPAP, PICU).'],
      expect: ['Recognises response to ventilation', 'Plans respiratory support and monitoring'], end: true },
    { name: 'Still HR < 60 despite ventilation', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 45, spo2: 72, rr: 30, etco2: 50, sbp: 50, dbp: 28 } }, ramp: 10000,
      cues: ['Start CPR (HR < 60 + poor perfusion). Adrenaline {adr}.', 'Atropine {atro} only if increased vagal tone or primary AV block.'],
      expect: ['Starts CPR for HR < 60 with poor perfusion', 'Adrenaline {adr}', 'Considers atropine appropriately'],
      next: [{ label: 'Responds ▶', to: 1 }] },
  ],
},
{
  id: 'sepsis', cat: 'Shock', title: 'Septic shock (toddler)',
  pt: { group: 'toddler', age: '18 mo', wt: 10, bed: 'Resus 1' },
  stem: 'An 18-month-old has had fever for 2 days and is now drowsy with a purpuric rash on the legs. Extremities are cool.',
  stages: [
    { name: 'Compensated shock', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 178, spo2: 95, rr: 42, etco2: 31, sbp: 86, dbp: 44, temp: 39.4 } }, ramp: 0,
      cues: ['Tachycardia + poor perfusion with normal BP = compensated shock.', 'IV/IO, bolus {bolus} and reassess (liver, crackles). Antibiotics within 1 h, check glucose and lactate.'],
      expect: ['Recognises compensated shock', 'Bolus 10–20 mL/kg with reassessment', 'Antibiotics within the first hour', 'Checks glucose, lactate, cultures'] },
    { name: 'Fluid-refractory, hypotensive', set: { rhythm: 'sinus', pulse: true, v: { hr: 188, sbp: 62, dbp: 30, spo2: 93, rr: 48 } }, ramp: 30000,
      cues: ['After 40–60 mL/kg: start adrenaline infusion 0.05–0.3 mcg/kg/min (or noradrenaline for warm shock), peripheral/IO acceptable.', 'Consider hydrocortisone if catecholamine-resistant.'],
      expect: ['Recognises fluid-refractory shock', 'Starts vasoactive infusion early', 'Watches for fluid overload', 'Considers intubation with haemodynamically safe induction'] },
    { name: 'Improving on vasoactive', set: { rhythm: 'sinus', pulse: true, v: { hr: 150, sbp: 88, dbp: 50, spo2: 97, rr: 36 } }, ramp: 45000,
      cues: ['Targets: normal mentation, CRT ≤ 2 s, urine output > 1 mL/kg/h, lactate falling.'],
      expect: ['Defines resuscitation end-points', 'Plans PICU transfer'] },
  ],
},
{
  id: 'dengue', cat: 'Shock', title: 'Dengue shock syndrome',
  pt: { group: 'child', age: '8 y', wt: 25, bed: 'Resus 2' },
  stem: 'An 8-year-old on day 5 of illness is now afebrile but has abdominal pain, vomiting and cold hands. NS1 was positive on day 2.',
  stages: [
    { name: 'Compensated: narrow pulse pressure', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 132, spo2: 98, rr: 26, etco2: 34, sbp: 96, dbp: 84, temp: 37.1 } }, ramp: 0,
      cues: ['Critical phase: pulse pressure ≤ 20 mmHg = compensated shock even with a "normal" SBP.', 'Check haematocrit; isotonic crystalloid per IAP dengue protocol (typically 10 mL/kg over 1 h, then step down).'],
      expect: ['Identifies narrow pulse pressure as shock', 'Sends baseline haematocrit', 'Starts crystalloid per protocol', 'Plans close monitoring (hourly vitals, urine output)'] },
    { name: 'Hypotensive shock', set: { rhythm: 'sinus', pulse: true, v: { hr: 152, sbp: 72, dbp: 58, spo2: 97, rr: 30 } }, ramp: 30000,
      cues: ['Bolus 20 mL/kg over 15–30 min per protocol, repeat haematocrit.', 'If haematocrit falls with unstable vitals, suspect bleeding and transfuse.'],
      expect: ['Recognises decompensation', 'Bolus with haematocrit-guided next step', 'Considers occult bleeding'] },
    { name: 'Improving', set: { rhythm: 'sinus', pulse: true, v: { hr: 108, sbp: 102, dbp: 70, rr: 24 } }, ramp: 45000,
      cues: ['Taper fluids early; watch for fluid overload in the recovery phase.'],
      expect: ['Plans fluid taper', 'Monitors for overload (respiratory distress, effusions)'] },
  ],
},
{
  id: 'asthma', cat: 'Respiratory', title: 'Status asthmaticus',
  pt: { group: 'child', age: '7 y', wt: 22, bed: 'Resus 1' },
  stem: 'A known asthmatic 7-year-old has had worsening breathlessness for 6 hours despite 3 salbutamol nebulisations at home. He can speak only single words.',
  stages: [
    { name: 'Severe exacerbation', set: { rhythm: 'sinus', pulse: true, cpr: false, co2Shape: 'obstructive', v: { hr: 152, spo2: 88, rr: 44, etco2: 48, sbp: 112, dbp: 70 } }, ramp: 0,
      cues: ['Point out the "shark-fin" capnogram (obstruction).', 'O₂, back-to-back salbutamol + ipratropium, systemic steroid, MgSO₄ {mgso4}.'],
      expect: ['Recognises life-threatening asthma', 'Back-to-back bronchodilators', 'Early steroids', 'Considers IV MgSO₄'] },
    { name: 'Tiring: silent chest', set: { rhythm: 'sinus', pulse: true, co2Shape: 'obstructive', v: { hr: 162, spo2: 82, rr: 18, etco2: 68 } }, ramp: 30000,
      cues: ['Falling RR with rising CO₂ = exhaustion, not improvement.', 'Prepare for intubation (ketamine); low rate, long expiratory time.'],
      expect: ['Recognises exhaustion from rising EtCO₂', 'Calls for senior / anaesthesia help', 'Safe intubation plan with low-rate ventilation'] },
    { name: 'Improving', set: { rhythm: 'sinus', pulse: true, co2Shape: 'normal', v: { hr: 128, spo2: 95, rr: 28, etco2: 40 } }, ramp: 45000,
      cues: ['Capnogram squares off as obstruction eases.'],
      expect: ['Plans PICU admission and weaning'] },
  ],
},
{
  id: 'scorpion', cat: 'Envenomation', title: 'Scorpion sting: autonomic storm',
  pt: { group: 'child', age: '5 y', wt: 18, bed: 'Resus 2' },
  stem: 'A 5-year-old was stung by a red scorpion 2 hours ago. He is sweating, vomiting and has cold extremities.',
  stages: [
    { name: 'Autonomic storm', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 162, spo2: 96, rr: 30, etco2: 34, sbp: 148, dbp: 100, temp: 37.8 } }, ramp: 0,
      cues: ['Hypertension, tachycardia, sweating, priapism: alpha-stimulation.', 'Prazosin {prazo} (IAP); repeat per response.'],
      expect: ['Recognises scorpion envenomation grade', 'Gives prazosin 30 mcg/kg', 'Monitors BP and for myocarditis'] },
    { name: 'Myocarditis, pulmonary oedema', set: { rhythm: 'sinus', pulse: true, v: { hr: 172, spo2: 84, rr: 52, etco2: 30, sbp: 74, dbp: 48 } }, ramp: 30000,
      cues: ['Cardiogenic shock with pulmonary oedema: avoid large boluses.', 'O₂ / CPAP or ventilation, dobutamine; echo.'],
      expect: ['Recognises cardiogenic shock and avoids fluid overload', 'Positive-pressure support', 'Inotrope (e.g. dobutamine)'] },
    { name: 'Stabilised', set: { rhythm: 'sinus', pulse: true, v: { hr: 130, spo2: 95, rr: 32, sbp: 96, dbp: 60 } }, ramp: 45000,
      cues: ['Continue monitoring in PICU.'],
      expect: ['Plans PICU care'] },
  ],
},
{
  id: 'anaph', cat: 'Shock', title: 'Anaphylaxis',
  pt: { group: 'child', age: '10 y', wt: 32, bed: 'Resus 1' },
  stem: 'A 10-year-old ate a peanut sweet at a party. Within minutes he developed hives, lip swelling, wheeze and dizziness.',
  stages: [
    { name: 'Anaphylactic shock', set: { rhythm: 'sinus', pulse: true, cpr: false, co2Shape: 'obstructive', v: { hr: 152, spo2: 90, rr: 36, etco2: 32, sbp: 74, dbp: 40 } }, ramp: 0,
      cues: ['IM adrenaline {adrim} anterolateral thigh, repeat every 5 min if needed.', 'High-flow O₂, lie flat, bolus {bolus}.'],
      expect: ['Gives IM adrenaline without delay', 'Correct dose and site', 'Fluid bolus for hypotension', 'Airway assessment (stridor)'] },
    { name: 'After 2 IM doses: still hypotensive', set: { rhythm: 'sinus', pulse: true, v: { hr: 160, sbp: 68, dbp: 36, spo2: 91 } }, ramp: 20000,
      cues: ['Refractory: adrenaline infusion; repeat fluids; prepare for difficult airway.'],
      expect: ['Recognises refractory anaphylaxis', 'Starts adrenaline infusion', 'Calls for airway expertise'] },
    { name: 'Improving', set: { rhythm: 'sinus', pulse: true, co2Shape: 'normal', v: { hr: 118, sbp: 100, dbp: 60, spo2: 97, rr: 24, etco2: 38 } }, ramp: 45000,
      cues: ['Observe for biphasic reaction; adrenaline auto-injector and allergy referral.'],
      expect: ['Plans observation period', 'Discharge plan with auto-injector'] },
  ],
},
{
  id: 'hyperk', cat: 'Rhythm', title: 'Hyperkalaemia: VT',
  pt: { group: 'adol', age: '12 y', wt: 40, bed: 'Resus 1' },
  stem: 'A 12-year-old with acute kidney injury (anuric for 24 hours) complains of weakness and palpitations.',
  stages: [
    { name: 'Wide-complex tachycardia with pulse', set: { rhythm: 'vt', pulse: true, cpr: false, v: { hr: 165, spo2: 95, rr: 26, etco2: 34, sbp: 84, dbp: 50 } }, ramp: 0,
      cues: ['Wide QRS tachycardia with pulse; poor perfusion means sync cardioversion {J0.5}–{J1}.', 'Treat hyperkalaemia: calcium {ca}, insulin + dextrose, salbutamol, bicarbonate {bicarb}.'],
      expect: ['Identifies wide-complex tachycardia', 'Assesses stability', 'Synchronised cardioversion if unstable', 'Gives calcium and shifts potassium'] },
    { name: 'Pulseless VT', set: arrest('vt', { v: { hr: 190, rr: 20 } }),
      cues: ['Now pulseless: CPR, defibrillate {J2} (unsynchronised).', 'Calcium {ca} during CPR.'],
      expect: ['Recognises loss of pulse', 'Turns SYNC off and defibrillates', 'Gives calcium during arrest'] },
    { name: 'ROSC', set: { rhythm: 'sinus', pulse: true, cpr: false, v: { hr: 112, spo2: 96, rr: 22, etco2: 42, sbp: 96, dbp: 58 } }, ramp: 20000,
      cues: ['Arrange urgent dialysis; repeat potassium.'],
      expect: ['Plans definitive therapy (dialysis)', 'Repeats blood gas / potassium'] },
  ],
},
];
})();
